---
booktitle: Proceedings of KDD-Cup 2009 Competition
publisher: PMLR
logoright: kdd09-150.jpg
supplementalurl: supplemental/JMLRWCP_V7_supplemental.html
volume: 7
year: '2009'
start: 2009-06-28
end: 2009-06-28
published: 2009-12-04
shortname: KDD-Cup 2009
sections:
- name: supplemental
  title: Supplemental
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: DrorKDD2099
month: 0
abstract: ''
editor:
- given: Gideon
  family: Dror
- given: Mar
  family: Boullé
- given: Isabelle
  family: Guyon
- given: Vincent
  family: Lemaire
- given: David
  family: Vogel
title: Proceedings of KDD-Cup 2009 Competition
email: ''
description: Proceedings of KDD-Cup 2009 Competition, New York, New York, USA
url: http://proceedings.mlr.press
baseurl: "/v7"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v7
conference:
  name: KDD-Cup 2009 Competition
  url: 
  location: New York, New York, USA
  dates:
  - 2009-06-28
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v7.bib
